### ISSUE TITLE
Wrong namespace for AlphaVantage\API\Master;

### ISSUE THREAD

**Issue by emmerink** [d1am0nd/alpha-vantage#1]
The classes that extend Master fail to do so because the use uses a wrong namespace with API in capitals. This should be changed to:

`use AlphaVantage\Api\Master;`

instead of:

`use AlphaVantage\API\Master;`

(or the directory should be renamed)

It throws:
`Symfony\Component\Debug\Exception\FatalErrorException: Class 'AlphaVantage\API\Master' not found in .../vendor/d1am0nd/alpha-vantage/src/Api/Stock.php`

**Comment by d1am0nd** [comment]
Thanks for noticing and the pull requests. Fixed.
